// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AuthService.proto

package AuthService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DisableTokenResp struct {
	IsSuccessfull        bool     `protobuf:"varint,1,opt,name=isSuccessfull,proto3" json:"isSuccessfull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DisableTokenResp) Reset()         { *m = DisableTokenResp{} }
func (m *DisableTokenResp) String() string { return proto.CompactTextString(m) }
func (*DisableTokenResp) ProtoMessage()    {}
func (*DisableTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a18c0ba073015190, []int{0}
}

func (m *DisableTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableTokenResp.Unmarshal(m, b)
}
func (m *DisableTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableTokenResp.Marshal(b, m, deterministic)
}
func (m *DisableTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableTokenResp.Merge(m, src)
}
func (m *DisableTokenResp) XXX_Size() int {
	return xxx_messageInfo_DisableTokenResp.Size(m)
}
func (m *DisableTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_DisableTokenResp proto.InternalMessageInfo

func (m *DisableTokenResp) GetIsSuccessfull() bool {
	if m != nil {
		return m.IsSuccessfull
	}
	return false
}

type User struct {
	Emac                 string   `protobuf:"bytes,1,opt,name=emac,proto3" json:"emac,omitempty"`
	Mboard               string   `protobuf:"bytes,2,opt,name=mboard,proto3" json:"mboard,omitempty"`
	Panel                string   `protobuf:"bytes,3,opt,name=panel,proto3" json:"panel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a18c0ba073015190, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmac() string {
	if m != nil {
		return m.Emac
	}
	return ""
}

func (m *User) GetMboard() string {
	if m != nil {
		return m.Mboard
	}
	return ""
}

func (m *User) GetPanel() string {
	if m != nil {
		return m.Panel
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_a18c0ba073015190, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a18c0ba073015190, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*DisableTokenResp)(nil), "AuthService.DisableTokenResp")
	proto.RegisterType((*User)(nil), "AuthService.User")
	proto.RegisterType((*Token)(nil), "AuthService.Token")
	proto.RegisterType((*Error)(nil), "AuthService.Error")
}

func init() { proto.RegisterFile("AuthService.proto", fileDescriptor_a18c0ba073015190) }

var fileDescriptor_a18c0ba073015190 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x6a, 0xf3, 0x30,
	0x10, 0xc5, 0x49, 0x1c, 0xf2, 0x4d, 0x08, 0x5f, 0x33, 0xfd, 0xc1, 0x84, 0x52, 0x82, 0xe8, 0x22,
	0x64, 0x11, 0x43, 0xba, 0x29, 0x81, 0x2e, 0x0a, 0x29, 0x74, 0xed, 0xf4, 0x67, 0x59, 0x14, 0x67,
	0x9a, 0x88, 0x3a, 0x96, 0x91, 0xe4, 0x1c, 0xa0, 0x57, 0xe8, 0x35, 0x7a, 0x9b, 0x5e, 0xa1, 0x07,
	0x29, 0x92, 0xbc, 0xb0, 0x21, 0xbb, 0x79, 0x6f, 0x9e, 0xde, 0xcc, 0x3c, 0xc1, 0xf0, 0xbe, 0x34,
	0xbb, 0x15, 0xa9, 0x83, 0x48, 0x69, 0x56, 0x28, 0x69, 0x24, 0xf6, 0x6b, 0xd4, 0xe8, 0x72, 0x2b,
	0xe5, 0x36, 0xa3, 0x98, 0x17, 0x22, 0xe6, 0x79, 0x2e, 0x0d, 0x37, 0x42, 0xe6, 0xda, 0x4b, 0xd9,
	0x2d, 0x9c, 0x2c, 0x85, 0xe6, 0xeb, 0x8c, 0x9e, 0xe4, 0x07, 0xe5, 0x09, 0xe9, 0x02, 0xaf, 0x61,
	0x20, 0xf4, 0xaa, 0x4c, 0x53, 0xd2, 0xfa, 0xbd, 0xcc, 0xb2, 0x28, 0x18, 0x07, 0x93, 0x5e, 0xd2,
	0x24, 0xd9, 0x23, 0x74, 0x9e, 0x35, 0x29, 0x44, 0xe8, 0xd0, 0x9e, 0xa7, 0x4e, 0xf4, 0x2f, 0x71,
	0x35, 0x5e, 0x40, 0x77, 0xbf, 0x96, 0x5c, 0x6d, 0xa2, 0x96, 0x63, 0x2b, 0x84, 0x67, 0x10, 0x16,
	0x3c, 0xa7, 0x2c, 0x6a, 0x3b, 0xda, 0x03, 0xf6, 0x06, 0xa1, 0x1b, 0x6e, 0xdb, 0xc6, 0x16, 0x95,
	0x97, 0x07, 0x96, 0x3d, 0xf0, 0x4c, 0x78, 0xaf, 0x5e, 0xe2, 0x01, 0x4e, 0xa1, 0x4b, 0x4a, 0x49,
	0xa5, 0xa3, 0xf6, 0xb8, 0x3d, 0xe9, 0xcf, 0x71, 0x56, 0xcf, 0xe1, 0xc1, 0xb6, 0x92, 0x4a, 0xc1,
	0xee, 0x20, 0x74, 0x84, 0xdd, 0x35, 0x95, 0x1b, 0x72, 0xfe, 0x61, 0xe2, 0x6a, 0x1c, 0x43, 0x7f,
	0x43, 0x3a, 0x55, 0xa2, 0xb0, 0xb9, 0x54, 0x0b, 0xd7, 0xa9, 0xf9, 0x77, 0x00, 0xf5, 0x44, 0x71,
	0x09, 0x1d, 0x0b, 0x71, 0xd8, 0x18, 0x69, 0xc3, 0x18, 0x35, 0xb7, 0x70, 0x57, 0xb1, 0xf3, 0xcf,
	0x9f, 0xdf, 0xaf, 0xd6, 0x7f, 0x06, 0x31, 0x2f, 0xcd, 0x2e, 0xb6, 0x82, 0x45, 0x30, 0xc5, 0x57,
	0x18, 0xbc, 0xd8, 0x4b, 0xb8, 0xf1, 0xd1, 0xe3, 0x91, 0xb7, 0x47, 0xfd, 0xae, 0x9c, 0x5f, 0xc4,
	0x4e, 0xbd, 0x5f, 0xc3, 0x64, 0x11, 0x4c, 0xd7, 0x5d, 0xf7, 0xb3, 0x37, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x03, 0xf5, 0x2b, 0x8e, 0x19, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Auth(ctx context.Context, in *User, opts ...grpc.CallOption) (*Token, error)
	ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Auth(ctx context.Context, in *User, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/AuthService.AuthService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/AuthService.AuthService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Auth(context.Context, *User) (*Token, error)
	ValidateToken(context.Context, *Token) (*Token, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Auth(ctx context.Context, req *User) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedAuthServiceServer) ValidateToken(ctx context.Context, req *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService.AuthService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Auth(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService.AuthService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthService_Auth_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AuthService_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AuthService.proto",
}
